project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - overview.qmd
    - hardware.qmd
    - firmware.qmd
    - usage.qmd

website:
  title: "Air Analyzer"
  page-navigation: true

  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd

      - section: "Project Overview"
        contents:
          - href: overview.qmd
            text: "Overview"

      - section: "Hardware"
        contents:
          - href: hardware.qmd
            text: "Hardware"

      - section: "Firmware"
        contents:
          - href: firmware.qmd
            text: "Firmware"

      - section: "Usage"
        contents:
          - href: usage.qmd
            text: "Usage"

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
    toc-depth: 3
    number-sections: false
    code-fold: true
    code-copy: true